import Header from "@/Component/Header/Header";
import { Montserrat_Alternates } from "next/font/google";

import "./globals.css";
import Footer from "@/Component/Footer/Footer";
import Up from "@/Component/Up/Up";
import ThemProviders from "@/Providers/ThemProviders";
const inter = Montserrat_Alternates({ subsets: ["latin"],weight:["400","700"] });

export const metadata = {
  title: "Ahmed EL Rooby",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-[#F1F5F9] dark:bg-[#171717]`}>
        <ThemProviders>

        <Header />
        <Up />
        {children}
        
        <Footer />
        </ThemProviders>

      </body>
    </html>
  );
}
